[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "yaqs"
version = "0.1.0"
description = "Quantum simulation library designed primarily for simulation of open quantum systems, noisy quantum circuits, and noisy quantum hardware"
authors = [
  { name="Aaron Sander", email = "aaron.sander@tum.de" },
]
dependencies = [
  "numpy",
  "scipy",
  "qiskit",
  "opt_einsum",
  "tqdm"
]
readme = "README.md"
requires-python = ">=3.9"
