name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .  # Install yaqs in editable mode
          pip install -r requirements.txt  # If you have additional dependencies
          pip install pytest pytest-cov  # Ensure pytest and coverage are installed

      - name: Run tests with coverage
        run: |
          pytest --cov=yaqs --cov-report=xml --cov-report=term

      - name: Upload coverage to Codecov (optional)
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
